# .github/workflows/git-sync.yml

on:
  push:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: daizihan233/git-sync@v4
        with:
          source_repo: "https://bitbucket.org/huwo1/proxy_nodes.git"
          source_branch: "main"
          destination_repo: "https://daizihan233/proxy_nodes.git"
          destination_branch: "main"
